version: "3.9"

services:
  web:
    build: .
    container_name: csv_ingestor_web
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://kaggle:kaggle@db:5432/kaggle_data
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: kaggle_db
    environment:
      POSTGRES_USER: kaggle
      POSTGRES_PASSWORD: kaggle
      POSTGRES_DB: kaggle_data
    ports:
      - "5432:5432"
    volumes:
      - kaggle_pgdata:/var/lib/postgresql/data

volumes:
  kaggle_pgdata:
